this is final

diff --git a/.github/workflows/tf-checks.yaml b/.github/workflows/tf-checks.yaml
--- a/.github/workflows/tf-checks.yaml
+++ b/.github/workflows/tf-checks.yaml
@@ -15,101 +15,101 @@ permissions:
   contents: read   # This is required for actions/checkout
 
 jobs:
-    linting:
-        runs-on: ubuntu-latest
-        steps:
-            - name: Checkout repository
-              uses: actions/checkout@v4
+    # linting:
+    #     runs-on: ubuntu-latest
+    #     steps:
+    #         - name: Checkout repository
+    #           uses: actions/checkout@v4
 
-            - name: Set up Terraform
-              uses: hashicorp/setup-terraform@v3
-              with:
-                terraform_version: 1.10.5
+    #         - name: Set up Terraform
+    #           uses: hashicorp/setup-terraform@v3
+    #           with:
+    #             terraform_version: 1.10.5
 
-            - name: Install tflint
-              run: |
-                curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
+    #         - name: Install tflint
+    #           run: |
+    #             curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
 
-            - name: Run tflint
-              run: |
-                tflint --version
-                find . -type f -name "*.tf" | xargs -I {} dirname {} | sort -u | while read DIR; do
-                  echo "Running terraform linter in the : $DIR"
-                  (cd "$DIR" && tflint) || {
-                    echo "tflint failed in $DIR, please fix the issues"
-                    exit 1; 
-                  }
-                done
-    terraform-fmt:
-            needs: linting
-            runs-on: ubuntu-latest
-            steps:
-                - name: Checkout repository
-                  uses: actions/checkout@v4
+    #         - name: Run tflint
+    #           run: |
+    #             tflint --version
+    #             find . -type f -name "*.tf" | xargs -I {} dirname {} | sort -u | while read DIR; do
+    #               echo "Running terraform linter in the : $DIR"
+    #               (cd "$DIR" && tflint) || {
+    #                 echo "tflint failed in $DIR, please fix the issues"
+    #                 exit 1; 
+    #               }
+    #             done
+    # terraform-fmt:
+    #         needs: linting
+    #         runs-on: ubuntu-latest
+    #         steps:
+    #             - name: Checkout repository
+    #               uses: actions/checkout@v4
 
-                - name: Set up Terraform
-                  uses: hashicorp/setup-terraform@v3
-                  with:
-                    terraform_version: 1.10.5
+    #             - name: Set up Terraform
+    #               uses: hashicorp/setup-terraform@v3
+    #               with:
+    #                 terraform_version: 1.10.5
 
-                - name: Run terraform fmt
-                  run: |
-                    find . -type f -name "*.tf" | xargs -I {} dirname {} | sort -u | while read DIR; do
-                      echo "Running terraform fmt in the : $DIR"
-                      (cd "$DIR" && terraform fmt -check=true) || {
-                        echo "terraform fmt failed in $DIR, please run terraform fmt to fix the errors"
-                        exit 1;
-                      }
-                    done
+    #             - name: Run terraform fmt
+    #               run: |
+    #                 find . -type f -name "*.tf" | xargs -I {} dirname {} | sort -u | while read DIR; do
+    #                   echo "Running terraform fmt in the : $DIR"
+    #                   (cd "$DIR" && terraform fmt -check=true) || {
+    #                     echo "terraform fmt failed in $DIR, please run terraform fmt to fix the errors"
+    #                     exit 1;
+    #                   }
+    #                 done
     
-    terraform-validate: 
-        needs: terraform-fmt
-        runs-on: ubuntu-latest
-        steps:
-            - name: Checkout repository
-              uses: actions/checkout@v4
+    # terraform-validate: 
+    #     needs: terraform-fmt
+    #     runs-on: ubuntu-latest
+    #     steps:
+    #         - name: Checkout repository
+    #           uses: actions/checkout@v4
 
-            - name: Set up Terraform
-              uses: hashicorp/setup-terraform@v3
-              with:
-                terraform_version: 1.10.5
-            - name: Install tflint
-              run: |
-               curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
+    #         - name: Set up Terraform
+    #           uses: hashicorp/setup-terraform@v3
+    #           with:
+    #             terraform_version: 1.10.5
+    #         - name: Install tflint
+    #           run: |
+    #            curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
       
-            - name: Run terraform validate
-              run: |
-                find . -type f -name "*.tf" | xargs -I {} dirname {} | sort -u | while read DIR; do
-                  echo "Running terraform validate in the : $DIR"
-                  (cd "$DIR" && terraform init -input=false -backend=false && terraform validate && tflint) || { 
-                    echo "terraform validate failed in $DIR, please fix the errors"; 
-                    exit 1; 
-                  }
-                done
-    tfsec:
-        needs: terraform-validate
-        runs-on: ubuntu-latest
-        steps:
-            - name: Checkout repository
-              uses: actions/checkout@v4
+    #         - name: Run terraform validate
+    #           run: |
+    #             find . -type f -name "*.tf" | xargs -I {} dirname {} | sort -u | while read DIR; do
+    #               echo "Running terraform validate in the : $DIR"
+    #               (cd "$DIR" && terraform init -input=false -backend=false && terraform validate && tflint) || { 
+    #                 echo "terraform validate failed in $DIR, please fix the errors"; 
+    #                 exit 1; 
+    #               }
+    #             done
+    # tfsec:
+    #     needs: terraform-validate
+    #     runs-on: ubuntu-latest
+    #     steps:
+    #         - name: Checkout repository
+    #           uses: actions/checkout@v4
 
-            - name: Set up Terraform
-              uses: hashicorp/setup-terraform@v3
-              with:
-                 terraform_version: 1.10.5
+    #         - name: Set up Terraform
+    #           uses: hashicorp/setup-terraform@v3
+    #           with:
+    #              terraform_version: 1.10.5
 
-            - name: Install tfsec
-              run: |
-                curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
-                apt update && apt install -y golang-go
-                go install github.com/aquasecurity/tfsec/cmd/tfsec@latest
-                tfsec --version
-            - name: Run tfsec
-              run: |
-                echo "Running tfsec for severity CRITICAL"
-                tfsec . -m CRITICAL
-                echo "Running tfsec detailed report"
-                tfsec . --run-statistics
+    #         - name: Install tfsec
+    #           run: |
+    #             curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
+    #             apt update && apt install -y golang-go
+    #             go install github.com/aquasecurity/tfsec/cmd/tfsec@latest
+    #             tfsec --version
+    #         - name: Run tfsec
+    #           run: |
+    #             echo "Running tfsec for severity CRITICAL"
+    #             tfsec . -m CRITICAL
+    #             echo "Running tfsec detailed report"
+    #             tfsec . --run-statistics
     service-build:
       # needs: tfsec
       runs-on: ubuntu-latest
@@ -125,41 +125,41 @@ jobs:
               python -m pip install --upgrade pip
               pip install -r service/requirements.txt -t service/python/
 
-    terraform-deploy:
-        needs:
-          - tfsec
-          - service-build
-        runs-on: ubuntu-latest
-        steps:
-            - name: Checkout code
-              uses: actions/checkout@v4
+    # terraform-deploy:
+    #     needs:
+    #       - tfsec
+    #       - service-build
+    #     runs-on: ubuntu-latest
+    #     steps:
+    #         - name: Checkout code
+    #           uses: actions/checkout@v4
 
-            - name: Set up Terraform
-              uses: hashicorp/setup-terraform@v3
-              with:
-                terraform_version: 1.10.5
+    #         - name: Set up Terraform
+    #           uses: hashicorp/setup-terraform@v3
+    #           with:
+    #             terraform_version: 1.10.5
             
-            - name: configure aws auth
-              uses: aws-actions/configure-aws-credentials@v4.0.3
-              with:
-                role-to-assume: ${{ env.GITHUB_ROLE_ARN }}
-                role-session-name: GitHub_to_AWS_via_FederatedOIDC
-                aws-region: ${{ env.AWS_REGION }}
+    #         - name: configure aws auth
+    #           uses: aws-actions/configure-aws-credentials@v4.0.3
+    #           with:
+    #             role-to-assume: ${{ env.GITHUB_ROLE_ARN }}
+    #             role-session-name: GitHub_to_AWS_via_FederatedOIDC
+    #             aws-region: ${{ env.AWS_REGION }}
 
-            - name: Initialize Terraform plan and apply in ${{env.environment}}
-              env:
-                environment: stg
-              run: |
-                cd $GITHUB_WORKSPACE/infrastructure/lambda
-                echo -e "\033[0;32mRunning terraform init in: $(basename $(pwd))\033[0m"
-                terraform init -reconfigure
-                terraform workspace new ${{env.environment}} || terraform workspace select ${{env.environment}} 
-                terraform plan --var-file="${{env.environment}}.tfvars" 
-                terraform apply --var-file="${{env.environment}}.tfvars" -auto-approve || exit 1
+    #         - name: Initialize Terraform plan and apply in ${{env.environment}}
+    #           env:
+    #             environment: stg
+    #           run: |
+    #             cd $GITHUB_WORKSPACE/infrastructure/lambda
+    #             echo -e "\033[0;32mRunning terraform init in: $(basename $(pwd))\033[0m"
+    #             terraform init -reconfigure
+    #             terraform workspace new ${{env.environment}} || terraform workspace select ${{env.environment}} 
+    #             terraform plan --var-file="${{env.environment}}.tfvars" 
+    #             terraform apply --var-file="${{env.environment}}.tfvars" -auto-approve || exit 1
 
-                cd $GITHUB_WORKSPACE/infrastructure/s3
-                terraform init -reconfigure
-                terraform workspace new ${{env.environment}} || terraform workspace select ${{env.environment}} 
-                terraform plan --var-file="${{env.environment}}.tfvars" 
-                terraform apply --var-file="${{env.environment}}.tfvars" -auto-approve || exit 1
+    #             cd $GITHUB_WORKSPACE/infrastructure/s3
+    #             terraform init -reconfigure
+    #             terraform workspace new ${{env.environment}} || terraform workspace select ${{env.environment}} 
+    #             terraform plan --var-file="${{env.environment}}.tfvars" 
+    #             terraform apply --var-file="${{env.environment}}.tfvars" -auto-approve || exit 1
                 
